---
title: "Supplementary Tables"
author: "Justin Bogias"
date: "`r format(Sys.Date(), '%d %b, %Y')`"
output:
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warnings = FALSE)
```

# Load Packages
```{r loadPackages, warning=FALSE, message=FALSE}
library(tidyverse)
library(edgeR)
library(magrittr)
library(ggplot2)
library(pheatmap)
library(VennDiagram)
library(AnnotationHub)
library(DT)
library(here)
```

# Load data
Load the results from each analysis
```{r significance_data}
oxygenGenes <- read_csv(here("data/results/oxygenGenes.csv.gz"))
oxygenTranscripts <- read_csv(here("data/results/oxygenTranscripts.csv.gz"))
oxygenDTU <- read_csv(here("data/results/oxygenDTU.csv.gz"))
```

# Supp table 1 - Highest expressed transcripts
```{r}
top_expressed <- oxygenTranscripts %>%
  dplyr::arrange(desc(logCPM)) %>%
  dplyr::select("Gene" = "GeneName",
                "Transcript" = "TranscriptName", 
                "Transcript Biotype" = "Transcript_biotype",
                "Transcript Length" = "length",
                "logCPM") 

top_expressed$logCPM <- format(round(top_expressed$logCPM, 1), nsmall = 1)

top_expressed %>%
  datatable()

write_csv(top_expressed, here("data/results/top_expressed_transcripts.csv"))
```

# Supp table 2 - triple overlap genes
```{r}
sig_genes <- oxygenGenes %>%
  dplyr::filter(FDR < 0.05 & abs(logFC) > 1) %>%
  dplyr::select("Gene",
                "GeneName",
                "DGE logFC" = "logFC",
                "DGE FDR" = "FDR")

sig_tx <- oxygenTranscripts %>%
  dplyr::filter(FDR < 0.05 & abs(logFC) > 1) %>%
  dplyr::select("Gene",
                "Transcript",
                "TranscriptName",
                "DTE logFC" = "logFC",
                "DTE FDR" = "FDR")

sig_dtu <- oxygenDTU %>%
  dplyr::filter(geneFDR < 0.05) %>%
  dplyr::select("Gene",
                "gene_name",
                "DTU FDR" = "geneFDR")

triple_overlap <- sig_tx %>%
  inner_join(sig_genes,
            by = "Gene") %>%
  inner_join(sig_dtu,
            by = "Gene")

sig_tx %>%
  inner_join(sig_genes,
            by = "Gene") %>%
  inner_join(sig_dtu,
            by = "Gene") %>%
  distinct() %>%
  datatable()
```

# Supp table 3 - DTE results
```{r de_tx}
oxygenTranscripts %>%
  dplyr::select("Transcript ID" = "Transcript",
                "Transcript Name" = "TranscriptName",
                "Gene ID" = "Gene",
                "Gene Name" = "GeneName",
                "logCPM",
                "logFC",
                "FDR") %>%
  dplyr::filter(FDR < 0.05 & abs(logFC) > 1) %>%
  datatable()
```

```{r up_regulated}
oxygenTranscripts %>%
  dplyr::select("Transcript ID" = "Transcript",
                "Transcript Name" = "TranscriptName",
                "Gene ID" = "Gene",
                "Gene Name" = "GeneName",
                "logCPM",
                "logFC",
                "FDR") %>%
  dplyr::filter(FDR < 0.05 & logFC >= 1) %>%
  datatable()
```

```{r down_regulated}
oxygenTranscripts %>%
  dplyr::select("Transcript ID" = "Transcript",
                "Transcript Name" = "TranscriptName",
                "Gene ID" = "Gene",
                "Gene Name" = "GeneName",
                "logCPM",
                "logFC",
                "FDR") %>%
  dplyr::filter(FDR < 0.05 & logFC <= -1) %>%
  datatable()
```

# Supp table 4 - Gene significant in DTE and DTU
```{r DTE_DTU_only}
sig_ranked_dtu <- sig_dtu %>%
  mutate(rank_in_dtu = 1:dim(sig_dtu)[1])

sig_ranked_dtu %>%
  dplyr::filter(Gene %in% sig_tx$Gene,
                !Gene %in% sig_genes$Gene) %>%
  dplyr::select("Gene",
                "gene_name",
                "DTU FDR",
                "rank_in_dtu") %>%
  inner_join(sig_tx %>%
              dplyr::select("Gene",
                            "Transcript",
                            "TranscriptName",
                            "DTE logFC",
                            "DTE FDR"),
            by = "Gene") %>%
  dplyr::select("Gene",
                "Transcript",
                "DTU FDR",
                "DTE FDR",
                "DTE logFC",
                "rank in DTU" = "rank_in_dtu") %>%
  mutate(`DTU FDR` = formatC(`DTU FDR`, digits = 2, width = 2, format = "e"),
         `DTE FDR` = formatC(`DTU FDR`, digits = 2, width = 2, format = "e"),
         `DTE logFC` = formatC(`DTE logFC`, digits = 3, width = 3)) %>%
  datatable()
```

# Supp table 5 - DTU results
```{r DTU_results}
oxygenDTU %>%
  dplyr::select("Gene",
                "Gene Name" = "gene_name",
                "Transcript",
                "Transcript Name" = "transcript_name",
                "Gene FDR" = "geneFDR",
                "Transcript FDR" = "txpFDR") %>%
  datatable()
```


