name: 07 Supplementary Tables

on:
  push:
    branches:
      - main
    paths:
      - 'markdowns/07_SupplementaryTables/**'

env:
  IMAGE_NAME: jbogias/placenta_dtu-07_supp_tbls
  IMAGE_TAG: latest
  DOCKER_USERNAME: jbogias

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Log into repository
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./markdowns/07_SupplementaryTables
          file: ./markdowns/07_SupplementaryTables/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
